server:
  port: 80
spring:
  datasource:
    password: 123
    username: root
    url: jdbc:mysql://localhost:3306/iot
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 175.27.245.91
    port: 6379
mybatis:
  type-aliases-package: xg.beans
  mapper-locations: [classpath:mapper/**/*.xml]
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
