server:
  port: 9000
spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos服务发现
    gateway:
      routes:
        - id: provider1 #路由id,只要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://provider-dept #使用服务名并负载均衡路由
          predicates: #断言，路径相匹配的才会进行uri/Path的路由
            - Path=/dept/**
            - After=2021-10-22T10:43:48.125+08:00[Asia/Shanghai]
            #- Cookie=phone,139
            #- Header=abc,\d+
            #- Query=productId,\d+
          filters:
            - AddRequestParameter=color,blue
            - AddRequestParameter=address,nj

        - id: provider2
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://provider-user
          predicates:
            - Path=/dept111/**
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名进行路由
