server:
  port: 8002

mybatis:
  type-aliases-package: xg.beans #所有Entity别名类所在包
  mapper-locations: [classpath:mapper/**/*.xml]
spring:
   application:
    name: provider-dept #在注册中心上显示的服务名
   cloud:
     nacos:
       discovery:
         server-addr: localhost:8848
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver #mysql驱动包
    url: jdbc:mysql://localhost:3306/cloud02 # 数据库名称
    username: root
    password: 123